# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


#project '/Users/arunkumar/Documents/ArunKumar/Harward_Git/FDA'

workspace 'FDA'

target 'FDA' do
    
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    # use_frameworks!
    
    # project 'FDA/FDA.xcodeproj'
    
    project '/Users/arunkumar/Documents/ArunKumar/Harward_Git/FDA/FDA.xcodeproj'
    
    # Pods for FDA
    #pod 'ResearchKit'
    
    pod 'IQKeyboardManager'
    
    
    
    target 'FDATests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'FDAUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
