project 'FDA.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FDA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FDA
  pod 'IQKeyboardManagerSwift'

  target 'FDATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FDAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
