project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

# Pods for FDA
def main_pods
  
   pod 'IQKeyboardManagerSwift', '6.5.5'
   pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
   pod 'SDWebImage', '5.8.0'
   pod 'RealmSwift', '5.0.0'
   pod 'CryptoSwift', '1.3.1'
   pod 'ActionSheetPicker-3.0', '2.5.0'

end

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  main_pods
  
end

target 'HPHCUITests' do
  use_frameworks!
  pod 'Embassy'
  pod 'EnvoyAmbassador'
end

target 'HPHCTests' do
  # inherit! :search_paths
  
  pod 'Mockingjay', '3.0.0-alpha.1'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
#    end
#  end
#end
